from __init__ import *

parseFile('parserinput/albacete_nextday.txt','parseroutput/albacete1d_50.drl','RtoDrools/albacete')
parseFile('parserinput/albacete_nextweek.txt','parseroutput/albacete7d_50.drl','RtoDrools/albacete')
parseFile('parserinput/albacete_twodays.txt','parseroutput/albacete2d_50.drl','RtoDrools/albacete')
parseFile('parserinput/antequera_nextday.txt','parseroutput/antequera1d_50.drl','RtoDrools/antequera')
parseFile('parserinput/segovia_nextday.txt','parseroutput/segovia1d_50.drl','RtoDrools/segovia')
parseFile('parserinput/segovia_twodays.txt','parseroutput/segovia2d_50.drl','RtoDrools/segovia')
parseFile('parserinput/segovia_nextweek.txt','parseroutput/segovia7d_50.drl','RtoDrools/segovia')
parseFile('parserinput/sevilla_nextday.txt','parseroutput/sevilla1d_50.drl','RtoDrools/segovia')

parseFile('parserinput/albacete_nextday.txt','parseroutput/albacete1d_all.drl','RtoDrools/albacete',0)
parseFile('parserinput/albacete_nextweek.txt','parseroutput/albacete7d_all.drl','RtoDrools/albacete',0)
parseFile('parserinput/albacete_twodays.txt','parseroutput/albacete2d_all.drl','RtoDrools/albacete',0)
parseFile('parserinput/antequera_nextday.txt','parseroutput/antequera1d_all.drl','RtoDrools/antequera',0)
parseFile('parserinput/segovia_nextday.txt','parseroutput/segovia1d_all.drl','RtoDrools/segovia',0)
parseFile('parserinput/segovia_twodays.txt','parseroutput/segovia2d_all.drl','RtoDrools/segovia',0)
parseFile('parserinput/segovia_nextweek.txt','parseroutput/segovia7d_all.drl','RtoDrools/segovia',0)
parseFile('parserinput/sevilla_nextday.txt','parseroutput/sevilla1d_all.drl','RtoDrools/segovia',0)

parseFile('parserinput/albacete_nextday.txt','parseroutput/albacete1d_70.drl','RtoDrools/albacete',0.7)
parseFile('parserinput/albacete_nextweek.txt','parseroutput/albacete7d_70.drl','RtoDrools/albacete',0.7)
parseFile('parserinput/albacete_twodays.txt','parseroutput/albacete2d_70.drl','RtoDrools/albacete',0.7)
parseFile('parserinput/antequera_nextday.txt','parseroutput/antequera1d_70.drl','RtoDrools/antequera',0.7)
parseFile('parserinput/segovia_nextday.txt','parseroutput/segovia1d_70.drl','RtoDrools/segovia',0.7)
parseFile('parserinput/segovia_twodays.txt','parseroutput/segovia2d_70.drl','RtoDrools/segovia',0.7)
parseFile('parserinput/segovia_nextweek.txt','parseroutput/segovia7d_70.drl','RtoDrools/segovia',0.7)
parseFile('parserinput/sevilla_nextday.txt','parseroutput/sevilla1d_70.drl','RtoDrools/segovia',0.7)
